---
- hosts: hadoop_ambari_nodes
  gather_facts: yes
  tasks:
   - include: tasks/set_ambari_facts.yml

- hosts: hadoop_primary_ambari_server_nodes
  roles:
    - { role: ambari,
        ambari_http: https,
        ambari_port: 8443,
        ambari_ranger_ssl: true }
