---
- name: Upgrade Ambari Agents
  yum:
    name: ambari-agent
    state: latest
  notify:
    - restart ambari_agent

- name: Upgrage Ambari Metrics
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ambari-metrics-monitor
    - ambari-metrics-hadoop-sink
