SN_REST_URL = 'https://{0}.service-now.com/api/now/table/{1}'
SN_REST_LIMIT = 'sysparm_limit={0}'
SN_REST_OFFSET = 'sysparm_offset={0}'
SN_REST_DISPLAY_VALUE = 'sysparm_display_value={0}'
SN_REST_QUERY = 'sysparm_query=active=true^u_monitored_by=4fd4cc0d6ff371041560e4bc5d3ee462'
SN_REST_QUERY_DATE = 'sysparm_query=active=true^sys_updated_on>javascript:gs.dateGenerate(\'{0}\',\'{1}\')^u_monitored_by=4fd4cc0d6ff371041560e4bc5d3ee462'

# TODO: Currently hardcoded
SN_UPDATE_LIMIT = 'sysparm_query=active=true^sys_updated_on>javascript:gs.dateGenerate(\'2016-11-10\',\'00:00:00\')'

CI_UNIX = 'cmdb_ci_unix_server'
CI_SOLARIS = 'cmdb_ci_solaris_server'
CI_LINUX = 'cmdb_ci_linux_server'
CI_WIN = 'cmdb_ci_win_server'
CI_ROUTER = 'cmdb_ci_ip_router'
CI_SWITCH = 'cmdb_ci_ip_switch'
CI_UPS = 'cmdb_ci_ups'
CI_VCENTER = 'cmdb_ci_vcenter'
CI_ESX = 'cmdb_ci_esx_server'
CI_STORAGE = 'cmdb_ci_msd'
CI_NETWORK_ADAPTER = 'cmdb_ci_network_adapter'

SN_NAME = 'name'
SN_ID = 'sys_id'
SN_CLASS_NAME = 'sys_class_name'
SN_MONITORED_BY = 'monitored_by'
SN_MANUFACTURER = 'manufacturer'
SN_IP_ADDRESS = 'ip_address'
SN_SNMP_VERSION = 'u_snmp_version'
SN_SUPPORT_TIER = 'u_support_tier'
SN_ENVIRONMENT = 'u_used_for'
SN_SUPPORT_GROUP = 'support_group'
SN_OPERATIONAL_STATUS = 'operational_status'
SN_LOCATION = 'location'
SN_LINUX_CLUSTER = 'linux_cluster'
SN_OS = 'os'
SN_DISPLAY_VALUE = 'display_value'

U_ENT_APP = 'u_enterprise_applications'

HTTP_VERB_POST = 'POST'
HTTP_VERB_PUT = 'PUT'
HTTP_VERB_GET = 'GET'
HTTP_VERB_DELETE = 'DELETE'
