# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "test"
    key                  = ".terraform.tfstate"
    resource_group_name  = "rg-dataright-terraform"
    storage_account_name = "stdatarightterraform"
  }
}
