PRIVILEGE_READ = 'read'
PRIVILEGE_ACK = 'ack'
PRIVILEGE_WRITE = 'write'

ROLE_PERMISSION_DEVICE = 'host_group'
ROLE_PERMISSION_DASHBOARD = 'dashboard_group'
ROLE_PERMISSION_REPORT = 'report_group'
ROLE_PERMISSION_SERVICE = 'service_group'
ROLE_PERMISSION_SETTING = 'setting'
ROLE_PERMISSION_HELP = 'help'

OBJ_STATUS = 'status'
OBJ_ERROR_MESSAGE = 'errmsg'
OBJ_DATA = 'data'
OBJ_ITEMS = 'items'
OBJ_ID = 'id'
OBJ_NAME = 'name'
OBJ_VALUE = 'value'
OBJ_LOCATION = 'location'
OBJ_HOST_GROUP_IDS = 'hostGroupIds'
OBJ_DISPLAY_NAME = 'displayName'
OBJ_CUSTOM_PROPERTIES = 'customProperties'
OBJ_COLLECTOR_ID = 'preferredCollectorId'
OBJ_DESCRIPTION = 'description'
OBJ_HOSTNAME = 'hostname'
OBJ_NUM_HOSTS = 'numberOfHosts'

TAB_DASHBOARD = 'dashboard'
TAB_DEVICE = 'device'
TAB_SERVICE = 'service'
TAB_SETTING = 'setting'
TAB_REPORT = 'report'
TAB_SDT = 'sdt'

ITEM_COLLECTOR = 'collectors'
ITEM_GROUPS = 'groups'
ITEM_ROLES = 'roles'
ITEM_FUNCTIONS = 'functions'
ITEM_DASHBOARDS = 'dashboards'
ITEM_RECIPIENT_GROUP = 'recipientgroups'
ITEM_ALERT = 'alert'
ITEM_CHAIN = 'chains'
ITEM_RULE = 'rules'
ITEM_DEVICES = 'devices'
ITEM_SERVICES = 'services'
ITEM_SDTS = 'sdts'
ITEM_TIMEZONE = 'timezone'

HTTP_VERB_POST = 'POST'
HTTP_VERB_PUT = 'PUT'
HTTP_VERB_GET = 'GET'
HTTP_VERB_DELETE = 'DELETE'

AUTH_TYPE_TOKEN = 'token'
AUTH_TYPE_BASIC = 'basic'

ALERT_SEVERITY_ERROR = 'Error'
ALERT_SEVERITY_WARNING = 'Warn'
ALERT_SEVERITY_CRITICAL = 'Critical'

LM_REST_URL = 'https://{0}.logicmonitor.com/santaba/rest/{1}/{2}'
LM_REST_URL_ID = 'https://{0}.logicmonitor.com/santaba/rest/{1}/{2}/{3}'
LM_REST_FILTER = '?filter={3}'
LM_REST_FILTER_NAME = '?filter=name:{3}'
LM_REST_FILTER_DISPLAYNAME = '?filter=displayName:{3}'
LM_REST_FILTER_DEVICEGROUPFULLPATH = '?filter=deviceGroupFullPath:{3}'
LM_REST_FILTER_FULLPATH = '?filter=fullPath:{3}'
LM_REST_FILTER_DEVICEGROUPID = '?filter=deviceGroupId:{3}'